// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tcp.Infrastructure.Persistence;

#nullable disable

namespace Tcp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TcpDbContext))]
    [Migration("20261007160228_ScimSchema")]
    partial class ScimSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tcp.Domain.Identity.ScimAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("ScimAudit", "idm");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("ScimGroup", "idm");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ScimGroupMember", "idm");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("EmailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailsSearch")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("GivenName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("GlobalUserId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PrimaryEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("GlobalUserId")
                        .IsUnique()
                        .HasFilter("[GlobalUserId] IS NOT NULL");

                    b.HasIndex("PrimaryEmail");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ScimUser", "idm", t =>
                        {
                            t.HasCheckConstraint("CK_ScimUser_EmailsJson", "ISJSON([EmailsJson]) = 1");

                            t.HasCheckConstraint("CK_ScimUser_RawJson", "ISJSON([RawJson]) = 1");
                        });
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroupMember", b =>
                {
                    b.HasOne("Tcp.Domain.Identity.ScimGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tcp.Domain.Identity.ScimUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimUser", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
