// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tcp.Infrastructure.Persistence;

#nullable disable

namespace Tcp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TcpDbContext))]
    [Migration("20261008103751_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Tcp.Domain.Identity.ScimAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("ScimAudit", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("ScimGroup", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ScimGroupMember", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("EmailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailsSearch")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("GivenName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("GlobalUserId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("GlobalUserId")
                        .IsUnique()
                        .HasFilter("\"GlobalUserId\" IS NOT NULL");

                    b.HasIndex("PrimaryEmail");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ScimUser", null, t =>
                        {
                            t.HasCheckConstraint("CK_ScimUser_EmailsJson", "json_valid(\"EmailsJson\")");

                            t.HasCheckConstraint("CK_ScimUser_RawJson", "json_valid(\"RawJson\")");
                        });
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.LocalIdSequence", b =>
                {
                    b.Property<string>("DefinitionLocalId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Day")
                        .HasColumnType("TEXT");

                    b.Property<int>("Next")
                        .HasColumnType("INTEGER");

                    b.HasKey("DefinitionLocalId", "Day");

                    b.ToTable("LocalIdSequence", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.OperationLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("At")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskUrn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("Id");

                    b.HasIndex("TaskUrn");

                    b.HasIndex("UserId");

                    b.ToTable("OperationLog", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskCustomAttribute", b =>
                {
                    b.Property<string>("TaskUrn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("TaskUrn", "Code");

                    b.ToTable("TaskCustomAttribute", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskDefinitionEntity", b =>
                {
                    b.Property<string>("Urn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomAttributesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDetailsSettingsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Urn");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.ToTable("TaskDefinition", null, t =>
                        {
                            t.HasCheckConstraint("CK_TaskDefinition_Json", "json_valid(\"NameJson\") AND json_valid(\"ResponsesJson\") AND json_valid(\"ActionsJson\") AND json_valid(\"CustomAttributesJson\") AND json_valid(\"CapabilitiesJson\")");
                        });
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskInstance", b =>
                {
                    b.Property<string>("Urn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("DefinitionUrn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("MEDIUM");

                    b.Property<string>("Processor")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Urn");

                    b.HasIndex("DefinitionUrn");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.HasIndex("Processor")
                        .HasDatabaseName("IX_TaskInstance_Processor")
                        .HasFilter("\"Processor\" IS NOT NULL");

                    b.HasIndex("ModifiedAt", "Urn")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskInstance_Pull");

                    b.ToTable("TaskInstance", null, t =>
                        {
                            t.HasCheckConstraint("CK_TaskInstance_Json", "json_valid(\"SubjectJson\") AND (\"DescriptionJson\" IS NULL OR json_valid(\"DescriptionJson\"))");

                            t.HasCheckConstraint("CK_TaskInstance_Priority", "\"Priority\" IN ('VERY_HIGH','HIGH','MEDIUM','LOW')");

                            t.HasCheckConstraint("CK_TaskInstance_Status", "\"Status\" IN ('READY','RESERVED','IN_PROGRESS','FOR_RESUBMISSION','INACTIVE','COMPLETED','CANCELED')");
                        });
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskOperationError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskUrn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("Id");

                    b.HasIndex("TaskUrn");

                    b.ToTable("TaskOperationError", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientGroup", b =>
                {
                    b.Property<string>("TaskUrn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("TaskUrn", "GroupName");

                    b.HasIndex("GroupName");

                    b.ToTable("TaskRecipientGroup", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientUser", b =>
                {
                    b.Property<string>("TaskUrn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<string>("GlobalUserId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.HasKey("TaskUrn", "GlobalUserId");

                    b.HasIndex("GlobalUserId");

                    b.ToTable("TaskRecipientUser", (string)null);
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroupMember", b =>
                {
                    b.HasOne("Tcp.Domain.Identity.ScimGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tcp.Domain.Identity.ScimUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskCustomAttribute", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("CustomAttributes")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskInstance", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("DefinitionUrn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskOperationError", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("OperationErrors")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientGroup", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("RecipientGroups")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientUser", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("RecipientUsers")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimUser", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskInstance", b =>
                {
                    b.Navigation("CustomAttributes");

                    b.Navigation("OperationErrors");

                    b.Navigation("RecipientGroups");

                    b.Navigation("RecipientUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
