// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tcp.Infrastructure.Persistence;

#nullable disable

namespace Tcp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TcpDbContext))]
    [Migration("20261007163542_TaskSchema")]
    partial class TaskSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tcp.Domain.Identity.ScimAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("ScimAudit", "idm");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("ScimGroup", "idm");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ScimGroupMember", "idm");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("EmailsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailsSearch")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("GivenName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("GlobalUserId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PrimaryEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("GlobalUserId")
                        .IsUnique()
                        .HasFilter("[GlobalUserId] IS NOT NULL");

                    b.HasIndex("PrimaryEmail");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ScimUser", "idm", t =>
                        {
                            t.HasCheckConstraint("CK_ScimUser_EmailsJson", "ISJSON([EmailsJson]) = 1");

                            t.HasCheckConstraint("CK_ScimUser_RawJson", "ISJSON([RawJson]) = 1");
                        });
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.LocalIdSequence", b =>
                {
                    b.Property<string>("DefinitionLocalId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("Day")
                        .HasColumnType("date");

                    b.Property<int>("Next")
                        .HasColumnType("int");

                    b.HasKey("DefinitionLocalId", "Day");

                    b.ToTable("LocalIdSequence", "tc");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.OperationLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TaskUrn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("TaskUrn");

                    b.HasIndex("UserId");

                    b.ToTable("OperationLog", "tc");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskCustomAttribute", b =>
                {
                    b.Property<string>("TaskUrn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TaskUrn", "Code");

                    b.ToTable("TaskCustomAttribute", "tc");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskDefinitionEntity", b =>
                {
                    b.Property<string>("Urn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapabilitiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomAttributesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskDetailsSettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Urn");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.ToTable("TaskDefinition", "tc", t =>
                        {
                            t.HasCheckConstraint("CK_TaskDefinition_Json", "ISJSON([NameJson]) = 1 AND ISJSON([ResponsesJson]) = 1 AND ISJSON([ActionsJson]) = 1 AND ISJSON([CustomAttributesJson]) = 1 AND ISJSON([CapabilitiesJson]) = 1");
                        });
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskInstance", b =>
                {
                    b.Property<string>("Urn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("DefinitionUrn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("DescriptionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LocalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("MEDIUM");

                    b.Property<string>("Processor")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("SubjectJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Urn");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Urn"), false);

                    b.HasIndex("DefinitionUrn");

                    b.HasIndex("LocalId")
                        .IsUnique();

                    b.HasIndex("Processor")
                        .HasDatabaseName("IX_TaskInstance_Processor")
                        .HasFilter("[Processor] IS NOT NULL");

                    b.HasIndex("ModifiedAt", "Urn")
                        .IsUnique()
                        .HasDatabaseName("IX_TaskInstance_Pull");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ModifiedAt", "Urn"));

                    b.ToTable("TaskInstance", "tc", t =>
                        {
                            t.HasCheckConstraint("CK_TaskInstance_Json", "ISJSON([SubjectJson]) = 1 AND ([DescriptionJson] IS NULL OR ISJSON([DescriptionJson]) = 1)");

                            t.HasCheckConstraint("CK_TaskInstance_Priority", "[Priority] IN ('VERY_HIGH','HIGH','MEDIUM','LOW')");

                            t.HasCheckConstraint("CK_TaskInstance_Status", "[Status] IN ('READY','RESERVED','IN_PROGRESS','FOR_RESUBMISSION','INACTIVE','COMPLETED','CANCELED')");
                        });
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskOperationError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TaskUrn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Id");

                    b.HasIndex("TaskUrn");

                    b.ToTable("TaskOperationError", "tc");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientGroup", b =>
                {
                    b.Property<string>("TaskUrn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("TaskUrn", "GroupName");

                    b.HasIndex("GroupName");

                    b.ToTable("TaskRecipientGroup", "tc");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientUser", b =>
                {
                    b.Property<string>("TaskUrn")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("GlobalUserId")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("TaskUrn", "GlobalUserId");

                    b.HasIndex("GlobalUserId");

                    b.ToTable("TaskRecipientUser", "tc");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroupMember", b =>
                {
                    b.HasOne("Tcp.Domain.Identity.ScimGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tcp.Domain.Identity.ScimUser", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskCustomAttribute", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("CustomAttributes")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskInstance", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskDefinitionEntity", null)
                        .WithMany()
                        .HasForeignKey("DefinitionUrn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskOperationError", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("OperationErrors")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientGroup", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("RecipientGroups")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskRecipientUser", b =>
                {
                    b.HasOne("Tcp.Domain.Tasks.TaskInstance", null)
                        .WithMany("RecipientUsers")
                        .HasForeignKey("TaskUrn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Tcp.Domain.Identity.ScimUser", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Tcp.Domain.Tasks.TaskInstance", b =>
                {
                    b.Navigation("CustomAttributes");

                    b.Navigation("OperationErrors");

                    b.Navigation("RecipientGroups");

                    b.Navigation("RecipientUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
